version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: energy-dashboard-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: energy_dashboard
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d energy_dashboard']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energy-dashboard-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: energy_dashboard
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # Optional: mount logs directory
      - ./logs:/app/logs

volumes:
  postgres_data:
    driver: local
